### ISSUE TITLE
AttributeError: 'FrankaServer' object has no attribute 'jacobian'

### ISSUE THREAD

**Issue by lightningboypro** [rail-berkeley/serl#31]
There is an error when running  python serl_robot_infra/robot_servers/franka_server.py on the real world franka robot. When we try to run, it gives this error:

[ERROR] [1709469050.695963]: bad callback: <bound method FrankaServer._set_currpos of <__main__.FrankaServer object at 0x7f0c4b5b5330>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/hyperarm/zichen/serl/serl_robot_infra/robot_servers/franka_server.py", line 161, in _set_currpos
    self.vel = self.jacobian @ self.dq
AttributeError: 'FrankaServer' object has no attribute 'jacobian'

[ERROR] [1709469050.730088]: bad callback: <bound method FrankaServer._set_currpos of <__main__.FrankaServer object at 0x7f0c4b5b5330>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/hyperarm/zichen/serl/serl_robot_infra/robot_servers/franka_server.py", line 161, in _set_currpos
    self.vel = self.jacobian @ self.dq
AttributeError: 'FrankaServer' object has no attribute 'jacobian'

[ERROR] [1709469050.764108]: bad callback: <bound method FrankaServer._set_currpos of <__main__.FrankaServer object at 0x7f0c4b5b5330>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/hyperarm/zichen/serl/serl_robot_infra/robot_servers/franka_server.py", line 161, in _set_currpos
    self.vel = self.jacobian @ self.dq
AttributeError: 'FrankaServer' object has no attribute 'jacobian'

Any help on how to solve this issue, or fixes to the codebase is appreciated!

**Comment by Leo428** [comment]
Hi @lightningboypro, we typically see this error message when launching the franka server for the first time on a real robot. Normally, if you just re-run the franka server command, this error should go away. @charlesxu0124 I remember you had a better fix for this.
