### ISSUE TITLE
Randomly getting EGL_BAD_ACCESS

### ISSUE THREAD

**Issue by lakshitadodeja** [rail-berkeley/serl#56]
Hi, 

I am using the franka sim environment provided by the repo and it is randomly throwing egl bad access error-  

```
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_BAD_ACCESS,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x74b97d1d51c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x74b97d14f140>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x74b97d14f140>,
                <OpenGL._opaque.EGLContext_pointer object at 0x74b94429e9c0>,
        ),
        result = 0
)
```

**Comment by 4ku** [comment]
Also have the similar problem:

```
(serl) ivan@ivanLenovo:~/Desktop/RL/serl/examples/async_drq_sim$ bash run_actor.sh 
WARNING:absl:Type handler registry overriding type "<class 'float'>" collision on scalar
WARNING:absl:Type handler registry overriding type "<class 'bytes'>" collision on scalar
WARNING:absl:Type handler registry overriding type "<class 'numpy.number'>" collision on scalar
2024-06-10 14:31:52.415599: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
rlds logger is not installed, install it if required: https://github.com/rail-berkeley/oxe_envlogger 
/home/ivan/.local/lib/python3.10/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/home/ivan/.local/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.9/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
Fatal Python error: Aborted
```

**Comment by 4ku** [comment]
Fixed it with:
```
sudo apt-get update
sudo apt-get install libgl1-mesa-glx libgl1-mesa-dri
export LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
sudo apt-get install libglfw3 libglfw3-dev
conda update libstdcxx-ng
conda install -c conda-forge gcc=11
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
pip install pytz
```

So I have 12-13 FPS on my RTX 3070 Ti Laptop GPU.

**Comment by 4ku** [comment]
> Hi! @4ku I still get this error after following your solution. Any other suggestions? Thanks!

Try reduce batch even more, for example 32 or 16

**Comment by parzivar** [comment]
i have met the same problem too
`(serl) robo@robot:~/work/serl$ python franka_sim/franka_sim/test/test_gym_env_human.py
/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Traceback (most recent call last):
  File "/home/robo/work/serl/franka_sim/franka_sim/test/test_gym_env_human.py", line 9, in <module>
    env = envs.PandaPickCubeGymEnv(action_scale=(0.1, 1))
  File "/home/robo/work/serl/franka_sim/franka_sim/envs/panda_pick_gym_env.py", line 148, in __init__
    self._viewer.render(self.render_mode)
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 706, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 730, in _get_viewer
    self.viewer = OffScreenViewer(
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 155, in __init__
    super().__init__(model, data, width, height, max_geom, visual_options)
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 53, in __init__
    self.viewport = mujoco.MjrRect(0, 0, width, height)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mujoco._render.MjrRect(left: int, bottom: int, width: int, height: int)

Invoked with: 0, 0, None, None
Exception ignored in: <function OffScreenViewer.__del__ at 0x7f4e525a9ea0>
Traceback (most recent call last):
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 202, in __del__
    self.free()
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 199, in free
    self.opengl_context.free()
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 125, in free
    EGL.eglDestroyContext(EGL_DISPLAY, self._context)
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglDestroyContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f4e8def24c0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f4e526f6a40>,
	),
	result = 0
)
Exception ignored in: <function GLContext.__del__ at 0x7f4e8dba9360>
Traceback (most recent call last):
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 130, in __del__
    self.free()
  File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 125, in free
    EGL.eglDestroyContext(EGL_DISPLAY, self._context)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglDestroyContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f4e8def24c0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f4e526f6a40>,
	),
	result = 0
)
`

**Comment by AMagd** [comment]
In the case of running "python franka_sim/franka_sim/test/test_gym_env_human.py" the error was due to missing height and width for viewer.. It was fixed in my case by adding those two manually in "franka_sim/franka_sim/envs/panda_pick_gym_env.py" after the declaration of self._viewer

```
        self._viewer = MujocoRenderer(
            self.model,
            self.data,
        )
        
        # add height and width to viewer
        self._viewer.height = render_spec.height
        self._viewer.width = render_spec.width
        
        self._viewer.render(self.render_mode)
```
