### ISSUE TITLE
UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64

### ISSUE THREAD

**Issue by parzivar** [rail-berkeley/serl#82]
when i run:  python franka_sim/franka_sim/test/test_gym_env_human.py
![image](https://github.com/user-attachments/assets/db3d6e5b-0ae6-429c-a8f0-3e2dfa416e87)
I am very interested in SERL， but i dont known how to solve this problem.
ubuntu20.04, Nvidia 565, cuda12.6,
I would be very grateful if you could reply me

**Comment by parzivar** [comment]
![Uploading image.png…]()

**Comment by claudio-dg** [comment]
Hi @parzivar, I get the exact same Error running it with Ubuntu 22.04 and Cuda 12.1. 
Hope someone replies as i am looking forward to reproduce their Simulation.

**Comment by CeyaoZhang** [comment]
Also encountered the same problem with Ubuntu 22.04 + CUDA 12.6.
Looking for the reply orz !!!

**Comment by youliangtan** [comment]
Check if this issue is relevant to:
- https://github.com/Farama-Foundation/Metaworld/issues/509
- https://github.com/google-deepmind/mujoco/issues/991

Referred to [here](https://github.com/google-deepmind/mujoco/issues/991#issuecomment-1875307602), on ubuntu setup, try adding `multiprocessing.set_start_method('spawn')` right after the import

**Comment by CeyaoZhang** [comment]
No, this error has nothing to do with operations like AsynVectorEnv or multiprocessing. The default code only concerns with one Env.

---

I also find that even run the following one line code 
```
from franka_sim import envs
env = envs.PandaPickCubeGymEnv(action_scale=(0.1, 1))
```
will cause 

> Traceback (most recent call last):
  File "/home/admin01/Projects/serl/franka_sim/franka_sim/test/test_gym_env_human.py", line 9, in <module>
    env = envs.PandaPickCubeGymEnv(action_scale=(0.1, 1))
  File "/home/admin01/Projects/serl/franka_sim/franka_sim/envs/panda_pick_gym_env.py", line 148, in __init__
    self._viewer.render(self.render_mode)
  File "/home/admin01/anaconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 706, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/home/admin01/anaconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 730, in _get_viewer
    self.viewer = OffScreenViewer(
  File "/home/admin01/anaconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 155, in __init__
    super().__init__(model, data, width, height, max_geom, visual_options)
  File "/home/admin01/anaconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 53, in __init__
    self.viewport = mujoco.MjrRect(0, 0, width, height)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mujoco._render.MjrRect(left: int, bottom: int, width: int, height: int)
> 
> Invoked with: 0, 0, None, None


After checking the code in `panda_pick_gym_env.py`, I doubt this result due to the missing inputs height and width in https://github.com/rail-berkeley/serl/blob/2f9f315b560790505b46a217c1653e7f2199566a/franka_sim/franka_sim/envs/panda_pick_gym_env.py#L144-L147

---

Looking forward your double check the sim code orz !!

**Comment by CeyaoZhang** [comment]
After setting 
```   
 self._viewer = MujocoRenderer(
            self.model,
            self.data,
            width=3,
            height=4
        )
```
the code works.

**Comment by CeyaoZhang** [comment]
Hi, @parzivar @claudio-dg , Can you check if this works for you too?
And I do suggest @parzivar  change this issus's title.
I missed this issue several times because the original title was about "UserWarning", which was not a really problem.

**Comment by parzivar** [comment]
Thank you for your questions, and I sincerely thank @CeyaoZhang and @youliangtan  for answering this question.
I have solved this problem by modifying the dependent version of the simulation environment, refer to https://github.com/rail-berkeley/serl/pull/76/commits/8ab8541567c80ca69a4503db07866783b7a00e3a
Finally, I made a fr3 robot teleoperation of an Xbox controller based on SERL. Interested friends can learn more about 
https://github.com/parzivar/Franka-Research-3-Robot-Simulation-with-Xbox-Controller-Integration-in-MuJoCo

**Comment by CeyaoZhang** [comment]
@parzivar  I check your method and it works.
 I think this issue lies in the different `gymnasium` versions.

**Comment by parzivar** [comment]
@CeyaoZhang  I have another question about SERL：https://github.com/rail-berkeley/serl/issues/47
If you have encountered and solved it, I hope you can give me some guidance, thank you

**Comment by CeyaoZhang** [comment]
I don't figure out your problem. You may give me more details and we can discuss in #47.
